--- #YAML:1.0
name:               Helios
version:            2.50_3160
abstract:           A system for distributed job processing applications.
author:
    - Andrew Johnson <lajandy at cpan dotorg>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Config::IniFiles:    2.38
    Data::ObjectDriver:  0.04
    DBI:                 1.52
    Error:               0.17
    Pod::Usage:          0.01
    Test::Simple:        0.72
    TheSchwartz:         1.04
    XML::Simple:         2.14
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
