--- #YAML:1.0
name:               MP3IndexerService
version:            1.00
abstract:           Helios service to index MP3s to a database table
author:
    - Andrew Johnson <lajandy at cpan dotorg>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Helios:     2.31
    MP3::Info:  1.24
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
